# For details: https://github.com/ericpre/ci-scripts
language: python

env:
  global:
    # The default environment variable are defined here and overwritten
    # in the matrix when necessary
    - ENV=pip
    - PIP_ARGS="--upgrade --use-feature=2020-resolver -e"
    - PIP_SELECTOR="all, tests, coverage"
    - PYTEST_ARGS="--pyargs hyperspy --reruns 3 -n 2 --instafail"
    - OLDEST_SUPPORTED_VERSION=false
    - MPLBACKEND="agg"

matrix:
  include:
  - name: "Linux, 3.8, pip"
    python: 3.8
  - name: "Linux, 3.7, pip"
    python: 3.7
    env: PYTEST_ARGS="$PYTEST_ARGS --cov=hyperspy"
  - name: "Linux, 3.6, pip"
    python: 3.6
  - name: "Linux, 3.7, pip, minimum requirement"
    env: PIP_SELECTOR="tests"
    python: 3.7
  - name: "Linux, 3.6, pip, oldest supported versions"
    env:
      - OLDEST_SUPPORTED_VERSION=true
      - PIP_ARGS="-e"
      - PIP_SELECTOR="tests"
    python: 3.6
  - name: "Linux, 3.7, pip, doc"
    env: PIP_SELECTOR="all, build-doc"
    python: 3.7

before_install:
  # Clone the ci-scripts repo to get the ci setup scripts
  - git clone --depth 1 git://github.com/hyperspy/ci-scripts.git
  - source ci-scripts/travis/setup_travis.sh

install:
  # Because of https://github.com/pypa/pip/issues/4391,
  # we need to update pytest manually.
  - pip install --upgrade pytest
  # Test against the oldest supported version of matplotlib, numpy and scipy
  - if [ "$OLDEST_SUPPORTED_VERSION" == true ]; then
      pip install matplotlib==2.2.3 numpy==1.15.4 scipy==1.1;
    fi
  - pip install $PIP_ARGS .["${PIP_SELECTOR}"];

script:
  - which python
  - python -c 'import matplotlib.pyplot as plt; print("Matplotlib backend:", plt.get_backend())';
  - if [[ $PIP_SELECTOR == *"build-doc"* ]]; then
      cd doc && make html;
    else
      echo "pytest arguments $PYTEST_ARGS";
      pytest $PYTEST_ARGS;
    fi

after_success:
  - if [[ $PYTEST_ARGS == *"--cov=hyperspy"* ]]; then
      codecov;
    fi
