#! /usr/bin/python
# To produce a binary-only deb file
# Requires python-stdeb, debhelper, dpkg-dev and python-argparser

import argparse

parser = argparse.ArgumentParser(description='Creates a debian package')

parser.add_argument('-i', '--install', action = 'store_true', 
                    help='Installs the program after packing it')

args = parser.parse_args()

import os
from subprocess import call
import lib.Release as Release
release_name = 'hyperspy-' + Release.version
os.system('python setup.py --command-packages=stdeb.command bdist_deb')

if args.install is True:
    os.system('sudo dpkg -i deb_dist/python-%s-1_all.deb' % 
    release_name.replace('hyperspy-', 'hyperspy_'))
    
